# -*- coding: utf-8 -*-
"""Checkers_Solver.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c0qTu4br3FlHUDwuf3R_T1ZNZWgItoYD
"""

import copy

class Player:
    def __init__(self, color):
        self.color = color  # 'red' or 'black'

    def __repr__(self):
        return f"Player({self.color})"

class Piece:
    def __init__(self, color, row, col, is_king=False):
        self.color = color  # 'red' or 'black'
        self.row = row
        self.col = col
        self.is_king = is_king

    def make_king(self):
        self.is_king = True

    def __repr__(self):
        return f"Piece({self.color}, ({self.row}, {self.col}), King={self.is_king})"

class GameBoard:
    def __init__(self):
        self.board = self._create_board()
        self.red_pieces = []
        self.black_pieces = []
        self._setup_pieces()

    def _create_board(self):
        # Initialize an 8x8 board with None values
        return [[None for _ in range(8)] for _ in range(8)]

    def _setup_pieces(self):
        # Place pieces in their initial positions
        for r in range(8):
            for c in range(8):
                if (r + c) % 2 != 0:  # Only place pieces on dark squares
                    if r < 3: # Black pieces on top rows
                        piece = Piece('black', r, c)
                        self.board[r][c] = piece
                        self.black_pieces.append(piece)
                    elif r > 4: # Red pieces on bottom rows
                        piece = Piece('red', r, c)
                        self.board[r][c] = piece
                        self.red_pieces.append(piece)

    def get_piece(self, row, col):
        if 0 <= row < 8 and 0 <= col < 8:
            return self.board[row][col]
        return None

    def move_piece(self, piece, new_row, new_col):
        # Clear old position
        self.board[piece.row][piece.col] = None
        # Update piece's position
        piece.row = new_row
        piece.col = new_col
        # Set new position
        self.board[new_row][new_col] = piece

        # Check for kinging
        if piece.color == 'red' and new_row == 0:
            piece.make_king()
        elif piece.color == 'black' and new_row == 7:
            piece.make_king()

    def remove_piece(self, piece):
        self.board[piece.row][piece.col] = None
        if piece.color == 'red':
            self.red_pieces.remove(piece)
        else:
            self.black_pieces.remove(piece)

    def display(self):
        # For console display
        print("  0 1 2 3 4 5 6 7")
        for r in range(8):
            print(f"{r} ", end="")
            for c in range(8):
                piece = self.board[r][c]
                if piece is None:
                    print("-", end=" ")
                else:
                    symbol = 'r' if piece.color == 'red' else 'b'
                    if piece.is_king:
                        symbol = symbol.upper()
                    print(symbol, end=" ")
            print()

class GameState:
    def __init__(self, board=None, current_player_color='red', move_history=None):
        self.board = board if board is not None else GameBoard()
        self.current_player_color = current_player_color
        self.move_history = move_history if move_history is not None else []
        self.winner = None

    def switch_player(self):
        self.current_player_color = 'black' if self.current_player_color == 'red' else 'red'

    def get_current_player(self):
        return Player(self.current_player_color)

    def get_opponent_player(self):
        return Player('black' if self.current_player_color == 'red' else 'red')

    def _get_player_pieces(self, color):
        return self.board.red_pieces if color == 'red' else self.board.black_pieces

    def get_valid_moves(self, piece=None):
        # Returns a list of (start_pos, end_pos, jumped_piece_pos) for the current player
        # If piece is specified, returns moves for that piece only
        valid_moves = []
        player_pieces = []

        if piece:
            player_pieces = [piece]
        else:
            player_pieces = self._get_player_pieces(self.current_player_color)

        # Check for mandatory jumps first
        mandatory_jumps = []
        for p in player_pieces:
            jumps = self._get_jumps(p)
            if jumps:
                mandatory_jumps.extend([( (p.row, p.col), (end_r, end_c), jumped_pos) for (end_r, end_c, jumped_pos) in jumps])

        if mandatory_jumps:
            return mandatory_jumps

        # If no mandatory jumps, then check for simple moves
        for p in player_pieces:
            moves = self._get_simple_moves(p)
            valid_moves.extend([( (p.row, p.col), (end_r, end_c), None) for (end_r, end_c) in moves])

        return valid_moves

    def _get_simple_moves(self, piece):
        moves = []
        direction = -1 if piece.color == 'red' else 1
        # Normal moves
        possible_moves = []
        if piece.is_king:
            possible_moves = [(piece.row + d, piece.col + dc) for d in [-1, 1] for dc in [-1, 1]]
        else:
            possible_moves = [(piece.row + direction, piece.col + dc) for dc in [-1, 1]]

        for r, c in possible_moves:
            if 0 <= r < 8 and 0 <= c < 8 and self.board.get_piece(r, c) is None:
                moves.append((r, c))
        return moves

    def _get_jumps(self, piece):
        jumps = []
        directions = [-1, 1] if piece.is_king else [(-1 if piece.color == 'red' else 1)]

        for dr in directions:
            for dc in [-1, 1]:
                mid_r, mid_c = piece.row + dr, piece.col + dc
                end_r, end_c = piece.row + 2 * dr, piece.col + 2 * dc

                if 0 <= end_r < 8 and 0 <= end_c < 8:
                    jumped_piece = self.board.get_piece(mid_r, mid_c)
                    if jumped_piece and jumped_piece.color != piece.color:
                        if self.board.get_piece(end_r, end_c) is None:
                            jumps.append((end_r, end_c, (mid_r, mid_c)))
        return jumps

    def make_move(self, start_pos, end_pos, jumped_piece_pos=None):
        # Create a new game state to represent the post-move board
        new_board = copy.deepcopy(self.board) # Deep copy the board and its pieces
        new_game_state = GameState(new_board, self.current_player_color, list(self.move_history))

        start_r, start_c = start_pos
        end_r, end_c = end_pos

        piece_to_move = new_board.get_piece(start_r, start_c)
        if not piece_to_move or piece_to_move.color != self.current_player_color:
            raise ValueError("No piece or not current player's piece at start position")

        new_board.move_piece(piece_to_move, end_r, end_c)

        if jumped_piece_pos:
            jumped_r, jumped_c = jumped_piece_pos
            jumped_piece = new_board.get_piece(jumped_r, jumped_c)
            if jumped_piece: # Ensure there was actually a piece to remove
                new_board.remove_piece(jumped_piece)
            else:
                raise ValueError("No piece found to jump at the given position.")

        new_game_state.move_history.append((start_pos, end_pos))

        # Check for further jumps (multi-jump)
        if jumped_piece_pos:
            further_jumps = new_game_state._get_jumps(new_board.get_piece(end_r, end_c))
            if further_jumps:
                # If there are more jumps, current player's turn doesn't end
                return new_game_state, True # Indicates multi-jump possibility

        new_game_state.switch_player()
        new_game_state.update_game_status() # Check for win/loss after move
        return new_game_state, False

    def update_game_status(self):
        red_pieces_count = len(self.board.red_pieces)
        black_pieces_count = len(self.board.black_pieces)

        if red_pieces_count == 0:
            self.winner = 'black'
        elif black_pieces_count == 0:
            self.winner = 'red'
        else:
            # Check if current player has any valid moves left
            current_player_has_moves = False
            for piece in self._get_player_pieces(self.current_player_color):
                if self._get_simple_moves(piece) or self._get_jumps(piece):
                    current_player_has_moves = True
                    break
            if not current_player_has_moves:
                self.winner = 'black' if self.current_player_color == 'red' else 'red'

    def is_game_over(self):
        return self.winner is not None

    def get_winner(self):
        return self.winner

def evaluate_board(game_state):
    # Heuristic evaluation function
    # Returns a win_pct for 'red' and 'black'

    red_score = 0
    black_score = 0

    # Piece count: basic advantage
    red_score += len(game_state.board.red_pieces) * 100
    black_score += len(game_state.board.black_pieces) * 100

    # King count: kings are more valuable
    for piece in game_state.board.red_pieces:
        if piece.is_king:
            red_score += 50 # Additional score for kings
    for piece in game_state.board.black_pieces:
        if piece.is_king:
            black_score += 50 # Additional score for kings

    # Piece advancement/position (optional, simple version)
    # Encourage pieces to move towards opponent's side and center
    for piece in game_state.board.red_pieces:
        red_score += (7 - piece.row) * 5 # Closer to opponent's king row (row 0)
        red_score += (3 - abs(piece.col - 3.5)) * 2 # Closer to center (col 3 or 4)
    for piece in game_state.board.black_pieces:
        black_score += piece.row * 5 # Closer to opponent's king row (row 7)
        black_score += (3 - abs(piece.col - 3.5)) * 2 # Closer to center (col 3 or 4)

    total_score = red_score + black_score
    if total_score == 0:
        # Should ideally not happen in a valid game state unless game is over and no pieces left
        return {'red': 0, 'black': 0}

    red_win_pct = (red_score / total_score) * 100
    black_win_pct = (black_score / total_score) * 100

    return {'red': round(red_win_pct, 2), 'black': round(black_win_pct, 2)}


# --- Example Usage --- #
if __name__ == '__main__':
    print("Initializing Checkers Game Backend...")

    # 1. Start a new game
    initial_game_state = GameState()
    print("Initial Board:")
    initial_game_state.board.display()
    print(f"Current Player: {initial_game_state.current_player_color}")

    # 2. Evaluate initial board
    initial_win_pct = evaluate_board(initial_game_state)
    print(f"Initial Win %: {initial_win_pct}")

    print("\n--- Simulating a few moves ---")
    current_state = initial_game_state

    # Example Move 1 (Red moves a piece)
    # Let's say red piece at (5,0) moves to (4,1)
    # Note: You'll need to find valid moves for actual gameplay logic
    # For demonstration, we'll try to force a simple move if it's available

    # Find a valid move for red
    red_moves = current_state.get_valid_moves()
    if red_moves:
        start_pos, end_pos, jumped_pos = red_moves[0]
        print(f"\nRed moving from {start_pos} to {end_pos}")
        try:
            current_state, is_multi_jump = current_state.make_move(start_pos, end_pos, jumped_pos)
            current_state.board.display()
            print(f"Current Player: {current_state.current_player_color}") # Should be black after red's turn
            win_pct = evaluate_board(current_state)
            print(f"Win % after Red's move: {win_pct}")
        except ValueError as e:
            print(f"Error making move for Red: {e}")
    else:
        print("No valid moves for Red.")

    # Example Move 2 (Black moves a piece)
    # Assuming the previous move was valid and it's now black's turn
    if not current_state.is_game_over() and current_state.current_player_color == 'black':
        black_moves = current_state.get_valid_moves()
        if black_moves:
            start_pos, end_pos, jumped_pos = black_moves[0]
            print(f"\nBlack moving from {start_pos} to {end_pos}")
            try:
                current_state, is_multi_jump = current_state.make_move(start_pos, end_pos, jumped_pos)
                current_state.board.display()
                print(f"Current Player: {current_state.current_player_color}") # Should be red after black's turn
                win_pct = evaluate_board(current_state)
                print(f"Win % after Black's move: {win_pct}")
            except ValueError as e:
                print(f"Error making move for Black: {e}")
        else:
            print("No valid moves for Black.")

    print("\n--- Game Status ---")
    if current_state.is_game_over():
        print(f"Game Over! Winner: {current_state.get_winner()}")
    else:
        print("Game still in progress.")